language: node_js
node_js:
- '10.0'
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - 139.162.142.155
before_install:
- openssl aes-256-cbc -K $encrypted_80564e2ae667_key -iv $encrypted_80564e2ae667_iv
  -in scripts/gatsby-deploy.enc -out scripts/gatsby-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/gatsby-deploy ~/.ssh/gatsby-deploy
- chmod 600 ~/.ssh/gatsby-deploy
- ssh-add ~/.ssh/gatsby-deploy
- echo -e "Host 139.162.142.155\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
